import type { IELTSTest } from "./types";

export const SAMPLE_TESTS: IELTSTest[] = [
  {
    id: "reading-city-gardens",
    title: "Urban Gardens · Test 1",
    module: "reading",
    trainingType: "academic",
    collection: "IELTS Scholars Originals",
    description: "A two-part academic reading practice with objective questions.",
    durationMinutes: 20,
    status: "published",
    passage: "Community gardens are changing the character of many modern cities. Once-empty plots are being converted into shared spaces where residents grow vegetables, learn practical skills, and meet neighbours. Researchers have linked regular participation with improved wellbeing and stronger community ties. However, successful gardens need clear rules, reliable access to water, and long-term support from local authorities. Some projects also reserve plots for schools, enabling children to observe seasonal change and understand where food comes from.",
    questions: [
      { id: "r1", type: "true-false-not-given", prompt: "Community gardens are always created on school property.", options: ["TRUE", "FALSE", "NOT GIVEN"], answer: "FALSE", points: 1 },
      { id: "r2", type: "multiple-choice", prompt: "What benefit is mentioned in the passage?", options: ["Lower transport costs", "Stronger community ties", "Free housing", "Longer working hours"], answer: "Stronger community ties", points: 1 },
      { id: "r3", type: "short-answer", prompt: "What resource must gardens have reliable access to?", answer: "water", points: 1 },
      { id: "r4", type: "true-false-not-given", prompt: "Every project reserves plots for schools.", options: ["TRUE", "FALSE", "NOT GIVEN"], answer: "FALSE", points: 1 },
      { id: "r5", type: "multiple-choice", prompt: "The main purpose of the passage is to discuss…", options: ["urban farming benefits and needs", "school examination rules", "commercial food exports", "city transport"], answer: "urban farming benefits and needs", points: 1 },
    ],
  },
  {
    id: "listening-campus-tour",
    title: "Campus Orientation · Test 1",
    module: "listening",
    trainingType: "academic",
    collection: "IELTS Scholars Originals",
    description: "Listening note-completion practice. Add your own audio URL from the admin panel.",
    durationMinutes: 10,
    status: "published",
    audioUrl: "",
    passage: "Demo transcript: The library opens at eight thirty on weekdays. New students should collect their cards from the welcome desk on the ground floor. Study rooms can be booked for a maximum of two hours.",
    questions: [
      { id: "l1", type: "short-answer", prompt: "The library opens at ____ on weekdays.", answer: "8:30", points: 1 },
      { id: "l2", type: "multiple-choice", prompt: "Where should students collect library cards?", options: ["First floor", "Welcome desk", "Bookshop", "Security office"], answer: "Welcome desk", points: 1 },
      { id: "l3", type: "short-answer", prompt: "Study rooms may be booked for a maximum of ____ hours.", answer: "2", points: 1 },
    ],
  },
  {
    id: "writing-remote-work",
    title: "Writing Task 2 · Remote Work",
    module: "writing",
    trainingType: "academic",
    collection: "IELTS Scholars Originals",
    description: "Opinion essay practice with live word count and autosaved draft.",
    durationMinutes: 40,
    status: "published",
    taskPrompt: "Some people believe working from home benefits employees and employers, while others think it damages teamwork. Discuss both views and give your own opinion.",
    questions: [{ id: "w1", type: "essay", prompt: "Write at least 250 words.", points: 9 }],
  },
  {
    id: "speaking-learning-skill",
    title: "Speaking Test · Learning a Skill",
    module: "speaking",
    trainingType: "general",
    collection: "IELTS Scholars Originals",
    description: "Three-part speaking practice with in-browser voice recording.",
    durationMinutes: 12,
    status: "published",
    speakingParts: [
      "Part 1: What skills are useful in your daily life? How do you usually learn something new?",
      "Part 2: Describe a skill you would like to learn. Say what it is, why you want to learn it, and how you would begin.",
      "Part 3: Should schools focus more on practical skills? How has technology changed learning?",
    ],
    questions: [{ id: "s1", type: "speaking-cue", prompt: "Record your response to the selected speaking part.", points: 9 }],
  },
];
